export const ENDPOINTS = {
  AUTH: {
    BASE: 'auth',
    REGISTER: 'register',
    VERIFY_EMAIL: 'verify-email',
    LOGIN: 'login',
    REFRESH: 'refresh',
    LOGOUT: 'logout',
    FORGOT_PASSWORD: 'forgot-password',
    RESET_PASSWORD: 'reset-password',
    ME: 'me',
    SESSIONS: 'sessions',
    SESSION_BY_ID: 'sessions/:sessionId',
    SESSIONS_REVOKE_OTHERS: 'sessions/revoke-others',
    SESSIONS_REVOKE_ALL: 'sessions/revoke-all',
    OAUTH_GOOGLE: 'google',
    OAUTH_GOOGLE_CALLBACK: 'google/callback',
    OAUTH_GITHUB: 'github',
    OAUTH_GITHUB_CALLBACK: 'github/callback',
    OAUTH_PROVIDERS: 'oauth/providers',
  },
  SETTINGS: {
    BASE: 'settings',
    APP_INFO: 'app-info',
    APP_INFO_LOGO: 'app-info/logo',
    APP_ANNOUNCEMENT: 'app-announcement',
    APP_MAINTENANCE: 'app-maintenance',
    BY_KEY: ':key',
  },
  WORKSPACES: {
    BASE: 'workspaces',
    BY_ID: ':id',
    MEMBERS: 'members',
    MEMBER_BY_ID: 'members/:memberId',
  },
  PROJECTS: {
    BASE: 'projects',
    BY_ID: ':id',
    MEMBERS: 'members',
    MEMBER_BY_ID: 'members/:memberId',
  },
  BOARDS: {
    BASE: 'boards',
    BY_PROJECT: 'project/:projectId',
    COLUMNS: ':boardId/columns',
    COLUMN_BY_ID: ':boardId/columns/:columnId',
    REORDER_COLUMNS: ':boardId/columns/reorder',
  },
  SPRINTS: {
    BASE: 'sprints',
    BY_ID: ':id',
    START: ':id/start',
    COMPLETE: ':id/complete',
    BURNDOWN: ':id/burndown',
  },
  ISSUES: {
    BASE: 'issues',
    BY_ID: ':id',
    BY_KEY: 'key/:key',
    MOVE: ':id/move',
    BULK_UPDATE: 'bulk',
    BULK_DELETE: 'bulk',
    LABELS: ':id/labels',
    LABEL_BY_ID: ':id/labels/:labelId',
    COMMENTS: ':id/comments',
    ATTACHMENTS: ':id/attachments',
    WORKLOGS: ':id/worklogs',
    ACTIVITY: ':id/activity',
    STAR: ':id/star',
    STARRED: 'me/starred',
    WATCH: ':id/watch',
    WATCHERS: ':id/watchers',
    LINKS: ':id/links',
    LINK_BY_ID: ':id/links/:linkId',
    EXPORT_CSV: 'export.csv',
  },
  LABELS: {
    BASE: 'labels',
    BY_ID: ':id',
  },
  COMMENTS: {
    BASE: 'comments',
    BY_ID: ':id',
  },
  ATTACHMENTS: {
    BASE: 'attachments',
    BY_ID: ':id',
  },
  WORKLOGS: {
    BASE: 'worklogs',
    BY_ID: ':id',
  },
  LOGS: {
    BASE: 'logs',
    BY_ID: ':id',
    CLIENT: 'client',
  },
  USERS: {
    BASE: 'users',
    BY_ID: ':id',
    ROLE: ':id/role',
    STATUS: ':id/status',
    SESSIONS: ':id/sessions',
    SESSION_BY_ID: ':id/sessions/:tokenId',
  },
  ADMIN: {
    BASE: 'admin',
    STATS: 'stats',
    ANALYTICS: 'analytics',
    METRICS: 'metrics',
    USER_ACTIVITY: 'user-activity',
    WORKSPACES: 'workspaces',
    WORKSPACE_BY_ID: 'workspaces/:id',
    AUDIT: 'audit',
    MAIL_LOGS: 'mail-logs',
    MAIL_LOG_BY_ID: 'mail-logs/:id',
    MAIL_LOG_STATS: 'mail-logs/stats',
    MAIL_LOG_CONFIG: 'mail-logs/config-status',
    MAIL_TEST: 'mail-logs/test',
  },
  FEATURE_FLAGS: {
    BASE: 'feature-flags',
    BY_ID: ':id',
    ME: 'me',
  },
  SAVED_FILTERS: {
    BASE: 'saved-filters',
    BY_ID: ':id',
  },
  ISSUE_TEMPLATES: {
    BASE: 'issue-templates',
    BY_ID: ':id',
  },
  ISSUE_LINKS: {
    BASE: 'issue-links',
    BY_ID: ':id',
  },
  NOTIFICATIONS: {
    BASE: 'notifications',
    BY_ID: ':id',
    READ: ':id/read',
    READ_ALL: 'read-all',
    UNREAD_COUNT: 'unread-count',
  },
} as const;
