export const MSG = {
  SUCCESS: {
    REGISTER: 'REGISTER_SUCCESS',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    LOGOUT: 'LOGOUT_SUCCESS',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD_SUCCESS',
    RESET_PASSWORD: 'RESET_PASSWORD_SUCCESS',
  },
  ERROR: {
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
    EMAIL_PENDING_VERIFICATION: 'EMAIL_PENDING_VERIFICATION',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
    APP_INFO_NOT_FOUND: 'APP_INFO_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  },
} as const;
